app.console.enabled=true

# Connexion Oracle
spring.datasource.url=jdbc:oracle:thin:@//gaia.emp.uqtr.ca:1521/coursbd.uqtr.ca
spring.datasource.username=SMI1002_050
spring.datasource.password=62ynye24
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

# Ne pas modifier la BD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.sql.init.mode=never